let data = [
  {
    'Area of Metroplex': 'Downtown Denton',
    'CHEW ': '3.5',
    City: '',
    Coordinates: '32.7845813, -97.34832209999999',
    Cuisine: 'Asian',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'Komodo Loco',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '4',
    City: 'Richardson',
    Coordinates: '32.8215641, -96.7869963',
    Cuisine: 'Chinese',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info':
      'http://places.singleplatform.com/first-emperor-barbecue-chinese-restaurant/menu?ref=google',
    'Name of Restaurant': 'First Emperor Chinese Restaurant',
    Notes: '',
    'Phone #': '19726809077',
    'Referred By': '',
    State: 'TX',
    Street: '200 W Polk St A',
    Website: 'http://www.firstemperorchinese.com/',
    'Zip ': '75081',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '4',
    City: 'Plano',
    Coordinates: '32.7991667, -96.7794444',
    Cuisine: 'German',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'https://bavariangrill.com/core-menu/',
    'Name of Restaurant': 'Bavarian Grill',
    Notes: '',
    'Phone #': '19728810705',
    'Referred By': '',
    State: 'TX',
    Street: '3425 Premier Dr,',
    Website: 'http://www.bavariangrill.com/',
    'Zip ': '75023',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '2.5',
    City: 'Carrollton',
    Coordinates: '32.8877661, -96.9636531',
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info':
      'https://www.elrincontx.com/carrollton/?utm_source=google&utm_medium=gmbmenu&utm_campaign=Carrollton&utm_term=mexicanrestaurant&utm_content=idgmb',
    'Name of Restaurant':
      'EL Rincon Mexican Kitchen & Tequila Bar - Carrollton Location',
    Notes: '',
    'Phone #': '14698926429',
    'Referred By': '',
    State: 'TX',
    Street: '1114 Elm St #100',
    Website:
      'https://www.elrincontx.com/carrollton/?utm_source=google&utm_medium=gmbhome&utm_campaign=Carrollton&utm_term=mexicanrestaurant&utm_content=idgmb',
    'Zip ': '75006',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '4',
    City: 'Dallas',
    Coordinates: '32.8805181, -96.88088359999999',
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'El Tiz Tizoncito Forest',
    Notes: 'Multiple Locations',
    'Phone #': '19722478797',
    'Referred By': '',
    State: 'TX',
    Street: '3318 Forest Ln #100',
    Website: 'http://www.tiztaco.com/',
    'Zip ': '75234',
  },
  {
    'Area of Metroplex': 'Dallas Deep Ellum',
    'CHEW ': '4',
    City: '',
    Coordinates: '33.0732863, -97.08089729999999',
    Cuisine: 'Japanese',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'Huwaiwa Japanese Sushi Bar',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Dallas',
    Coordinates: 'Not found',
    Cuisine: 'Mediterranean',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info':
      'http://places.singleplatform.com/fadis-mediterranean-grill/menu?ref=google',
    'Name of Restaurant': "Fadi's Mediterranean Grill",
    Notes: 'Multiple Locations',
    'Phone #': '12145281800',
    'Referred By': '',
    State: 'TX',
    Street: '3001 Knox St #110',
    Website: 'http://www.fadiscuisine.com/',
    'Zip ': '75205',
  },
  {
    'Area of Metroplex': 'Trinity River Bridge',
    'CHEW ': '4',
    City: '',
    Coordinates: '33.2163211, -97.1205226',
    Cuisine: 'Japanese',
    'Delivery Services': '',
    'IG/FB': '@tenramen',
    'Menu Info': '',
    'Name of Restaurant': 'Ten Ramen',
    Notes: 'The Colony',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Street: '',
    Website: 'https://www.tenramen.com/',
    'Zip ': '',
  },
  {
    'Area of Metroplex': 'Addison',
    'CHEW ': '4',
    City: 'Addison',
    Coordinates: '41.7292449, -88.04286119999999',
    Cuisine: 'Seafood General Cuisine',
    'Delivery Services': '',
    'IG/FB': '@leftyslobster',
    'Menu Info': '',
    'Name of Restaurant': 'Lefty’s ',
    Notes: '',
    'Phone #': '(972) 774-9518',
    'Referred By': '',
    State: 'TX',
    Street: '4021 Belt Line Rd',
    Website: 'http://www.leftyslobster.com/',
    'Zip ': '75001',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '4',
    City: 'Flower Mound',
    Coordinates: '33.1841222, -97.1075178',
    Cuisine: 'Pizza',
    'Delivery Services': 'yes',
    'IG/FB': '',
    'Menu Info': 'https://www.rosatispizza.com/location/flower-mound-tx/',
    'Name of Restaurant': 'Rosati’s',
    Notes: 'Multiple Locations',
    'Phone #': '19729069696',
    'Referred By': '',
    State: 'TX',
    Street: '2704 Cross Timbers Rd Suite 112',
    Website: 'https://www.rosatispizza.com/location/flower-mound-tx/',
    'Zip ': '75028',
  },
  {
    'Area of Metroplex': 'Northwest Dallas',
    'CHEW ': '3.5',
    City: 'Dallas',
    Coordinates: '33.1028218, -97.1897604',
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'https://elrincondeldf.com/menu/',
    'Name of Restaurant': 'El Rincon del D.F. (LaCapital de la Torta)',
    Notes: '',
    'Phone #': '214-350-0381 ',
    'Referred By': '',
    State: 'TX',
    Street: '2900 Wallnut Hill Ln, Ste 202 ',
    Website: 'https://elrincondeldf.com/',
    'Zip ': '75229',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3.5',
    City: 'Dallas',
    Coordinates: '32.9862133, -96.9126974',
    Cuisine: 'Mediterranean',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'https://cafeizmir.com/menu',
    'Name of Restaurant': 'Cafe Izmir Mediterranean Tapas',
    Notes: '',
    'Phone #': '12148267788',
    'Referred By': '',
    State: 'TX',
    Street: '3711 Greenville Ave.',
    Website: 'http://www.cafeizmir.com/',
    'Zip ': '75206',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: '32.9986014, -96.84512509999999',
    Cuisine: 'Donut',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'Good Morning Donuts',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': 'Downtown Denton',
    'CHEW ': '3.5',
    City: 'Denton',
    Coordinates: '33.1588514, -97.10469529999999',
    Cuisine: 'Middle Eastern/Jordanian',
    'Delivery Services': '',
    'IG/FB': 'https://www.facebook.com/1503921746492828',
    'Menu Info': 'https://www.layalinamediterraneanrestaurant.com/menu/',
    'Name of Restaurant': 'Layalina Mediterranean Restaurant and Lounge',
    Notes: '',
    'Phone #': '19403823663',
    'Referred By': '',
    State: 'TX',
    Street: '222 W Hickory St #104',
    Website: '',
    'Zip ': '76201',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: '32.8973795, -96.8717779',
    Cuisine: '',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'Tea Takaokaya',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': 'Downtown Denton',
    'CHEW ': '3.5',
    City: 'Denton',
    Coordinates: '37.4158854, -94.70368789999999',
    Cuisine: 'Greek Mediterranean',
    'Delivery Services': '',
    'IG/FB': '@gyrothreesixty ',
    'Menu Info': '',
    'Name of Restaurant': 'Gyro 360',
    Notes: '',
    'Phone #': '(940) 323-0003 ',
    'Referred By': '',
    State: 'TX',
    Street: '311 E Hickory St #110 ',
    Website: 'https://www.gyro360tx.com/ ',
    'Zip ': '76201',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '4',
    City: 'Denton',
    Coordinates: '32.9892425, -96.86684419999999',
    Cuisine: 'Hamburger',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info':
      'http://places.singleplatform.com/rg-burgers--grill/menu?ref=google',
    'Name of Restaurant': 'RG Burgers and Grill',
    Notes: '',
    'Phone #': '19403832431',
    'Referred By': '',
    State: 'TX',
    Street: '2430 S Interstate 35 Ste 172',
    Website: 'https://www.rgtexas.com/',
    'Zip ': '76205',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Dallas',
    Coordinates: '33.2142448, -97.1331589',
    Cuisine: 'Burger Sandwiches',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info':
      'http://places.singleplatform.com/maple-and-motor/menu?ref=google',
    'Name of Restaurant': 'Maple & Motor',
    Notes: '',
    'Phone #': '12145224400',
    'Referred By': '',
    State: 'TX',
    Street: '4810 Maple Ave',
    Website: 'http://mapleandmotor.com/',
    'Zip ': '75219',
  },
  {
    'Area of Metroplex': 'North Dallas/Richardson',
    'CHEW ': '4',
    City: 'Richardson',
    Coordinates: '33.0363765, -97.0745118',
    Cuisine: 'Chinese',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'Jeng Chi',
    Notes: 'Dumplings, Juices, ',
    'Phone #': '',
    'Referred By': '',
    State: 'TX',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: 'Not found',
    Cuisine: 'Tex Mex Mexican',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'Mattito’s Tex-Mex',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: '32.9409147, -96.9516392',
    Cuisine: 'American Hamburger Fusion Milkshake',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'Son of a Butcher',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': 'Multiple Locations',
    'CHEW ': '3',
    City: '',
    Coordinates: '33.1025656, -97.1892762',
    Cuisine: 'Burger Fusion',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'LA Burger',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Irving',
    Coordinates: '33.0346696, -97.0712626',
    Cuisine: 'Mexican Taqueria',
    'Delivery Services': '',
    'IG/FB': 'https://m.facebook.com/SanDiegoTacos/',
    'Menu Info':
      'http://places.singleplatform.com/san-diego-taco-shop-0/menu?ref=google',
    'Name of Restaurant': 'San Diego Tacos',
    Notes: 'Multiple Locations',
    'Phone #': '19725067064',
    'Referred By': '',
    State: 'TX',
    Street: '10000 N MacArthur Blvd,',
    Website: '',
    'Zip ': '75063',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '2.5',
    City: 'Dallas',
    Coordinates: '32.7971593, -96.77371',
    Cuisine: 'Mexican Seafood',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'http://www.mariscoslamarea.com/menu',
    'Name of Restaurant': 'Mariscos La Marina',
    Notes: '',
    'Phone #': '12143660703',
    'Referred By': '',
    State: 'TX',
    Street: '9404 Ovella Ave',
    Website: 'http://mariscoslamarina.com/',
    'Zip ': '75220',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3.5',
    City: 'Flower Mound',
    Coordinates: '32.822341, -96.83589119999999',
    Cuisine: 'Mediterranean',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'http://istanbulflowermound.com/',
    'Name of Restaurant': 'Istanbul Cuisine Flower Mound',
    Notes: '',
    'Phone #': '12145131333',
    'Referred By': '',
    State: 'TX',
    Street: '2911 Cross Timbers Rd #103',
    Website: 'https://www.istanbulflowermound.com/',
    'Zip ': '75028',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '4',
    City: 'Highland Village',
    Coordinates: '32.7496784, -97.3560994',
    Cuisine: 'General Fine Dining',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'https://www.hillsidegrillhighlandvillage.com/menu/',
    'Name of Restaurant': 'Hillside Fine Grill',
    Notes: 'Multiple Locations',
    'Phone #': '19723179711',
    'Referred By': '',
    State: 'TX',
    Street: '3140 FM 407',
    Website: 'https://www.hillsidegrillhighlandvillage.com/',
    'Zip ': '75077',
  },
  {
    'Area of Metroplex': 'Lewisville',
    'CHEW ': '3.5',
    City: 'Lewisville',
    Coordinates: 'Not found',
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'https://palapasseafoodbar.us//menu.php',
    'Name of Restaurant': 'Palapas Seafood Bar',
    Notes: '',
    'Phone #': '945-228-0441 ',
    'Referred By': '',
    State: 'TX',
    Street: '253 W Church St ',
    Website: 'https://palapasseafoodbar.us/',
    'Zip ': '75057',
  },
  {
    'Area of Metroplex': 'Little Korea Carrollton',
    'CHEW ': '3',
    City: 'Carrollton',
    Coordinates: '33.0455465, -96.7025482',
    Cuisine: 'Korean',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'https://www.ddongggotx.com/menu',
    'Name of Restaurant': 'Butt Hole Chicken (DDONG GGO TX)',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: 'TX',
    Street: '2625 Old Denton Rd #322 ',
    Website: 'https://www.ddongggotx.com/',
    'Zip ': '75056',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '0',
    City: '',
    Coordinates: '28.5402105, -81.3823168',
    Cuisine: '',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'Petra and The Beast',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': 'Forth Worth 7th Street',
    'CHEW ': '4',
    City: 'Fort Worth',
    Coordinates: 'Not found',
    Cuisine: 'Japanese Sushi',
    'Delivery Services': '',
    'IG/FB': 'http://instagram.com/HatsuyukiFW',
    'Menu Info': '',
    'Name of Restaurant': 'Hatsuyuki Handroll Bar',
    Notes: '',
    'Phone #': '18177205330',
    'Referred By': '',
    State: 'TX',
    Street: '907 Foch St',
    Website: '',
    'Zip ': '76107',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Carrollton',
    Coordinates: '33.073911, -97.07942249999999',
    Cuisine: 'Central American Salvadorian',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'http://orderrestaurantlatinotx.com/',
    'Name of Restaurant': 'Restaurant Latino',
    Notes: 'Papusas',
    'Phone #': '19724167195',
    'Referred By': '',
    State: 'TX',
    Street: '2660 Kelly Blvd',
    Website: '',
    'Zip ': '75007',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: 'Not found',
    Cuisine: '',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'Revolver Taco Lounge ',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': 'Trinity River Bridge',
    'CHEW ': '3.5',
    City: '',
    Coordinates: '36.0736294, -79.7904147',
    Cuisine: 'Italian',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'Cibo Diavello Market',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Denton',
    Coordinates: '33.2302974, -97.1816568',
    Cuisine: 'Greek Mediterranean',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': "Yummy's Greek ",
    Notes: '',
    'Phone #': '(940) 383-2441 ',
    'Referred By': '',
    State: 'TX',
    Street: '210 W University Dr ive',
    Website: 'https://www.yummysgreekfood.com/',
    'Zip ': '76201',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Denton',
    Coordinates: '32.1949801, -95.85479819999999',
    Cuisine: 'Southern',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'https://cartwrightsranchhouse.takeout7.com/',
    'Name of Restaurant': "Cartwright's Ranch House",
    Notes: '',
    'Phone #': '19403877706',
    'Referred By': '',
    State: 'TX',
    Street: '111 N Elm St',
    Website: 'http://www.cartwrightstexas.com/',
    'Zip ': '76201',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Dallas',
    Coordinates: '32.9547314, -96.8442185',
    Cuisine: 'Southern',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'https://www.luckyshotchicken.com/menu/',
    'Name of Restaurant': 'Lucky’s Hot Chicken',
    Notes: '',
    'Phone #': '12144437927',
    'Referred By': '',
    State: 'TX',
    Street: '4505 Gaston Ave',
    Website: 'https://www.luckyshotchicken.com/',
    'Zip ': '75246',
  },
  {
    'Area of Metroplex': 'Addison Farmers Branch',
    'CHEW ': '3.5',
    City: 'Carrollton',
    Coordinates: '32.8319881, -96.77051999999999',
    Cuisine: 'Latin Cuban',
    'Delivery Services': '',
    'IG/FB': '@caribbean_cuba',
    'Menu Info': '',
    'Name of Restaurant': 'Caribbean Cuba Cafe',
    Notes: '',
    'Phone #': '(469) 758-6047 ',
    'Referred By': '',
    State: 'TX',
    Street: '1000 Webb Chapel Rd',
    Website: 'http://mycaribbeancuba.com/',
    'Zip ': '75006',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Irving',
    Coordinates: '32.9399092, -97.1113342',
    Cuisine: 'Japanese',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'https://edokolascolinas.com/food-menu',
    'Name of Restaurant': 'Edoko Omakase',
    Notes: '',
    'Phone #': '19726008626',
    'Referred By': '',
    State: 'TX',
    Street: '1030 W John Carpenter Fwy #100',
    Website: 'https://edokolascolinas.com/',
    'Zip ': '75039',
  },
  {
    'Area of Metroplex': 'Loop12/35E',
    'CHEW ': '3',
    City: 'Dallas',
    Coordinates: '33.1030447, -97.1891184',
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'Cabrisitos',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: 'TX',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': 'Denton',
    'CHEW ': '0',
    City: '',
    Coordinates: '32.8483026, -96.991508',
    Cuisine: 'Japanese',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'Niwa Japanese BBQ',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': 'Lakewood',
    'CHEW ': '3.5',
    City: 'Dallas',
    Coordinates: '32.9942772, -97.06522439999999',
    Cuisine: 'Vietnamese',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'https://www.mothaibadallas.com/menu',
    'Name of Restaurant': 'Mot Hai Ba',
    Notes: '',
    'Phone #': ' (972) 638-7468 ',
    'Referred By': '',
    State: 'TX',
    Street: '6047 Lewis St ',
    Website: 'https://www.mothaibadallas.com/',
    'Zip ': '75206',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Denton',
    Coordinates: 'Not found',
    Cuisine: 'Burger ',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'https://www.lsaburger.com/good-eats',
    'Name of Restaurant': 'LSA Burger Co.',
    Notes: '',
    'Phone #': '19403831022',
    'Referred By': '',
    State: 'TX',
    Street: '113 W Hickory St',
    Website: 'http://www.lsaburger.com/',
    'Zip ': '76201',
  },
  {
    'Area of Metroplex': 'Downtown Dallas',
    'CHEW ': '4',
    City: 'Dallas',
    Coordinates: '33.1002911, -97.21353970000001',
    Cuisine: 'Thai',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'http://www.bangkokcityrestaurant.com/',
    'Name of Restaurant': 'Bangkok City Restaurant',
    Notes: '',
    'Phone #': '12148246200',
    'Referred By': '',
    State: 'TX',
    Street: '4301 Bryan St #101',
    Website: 'https://www.bangkokcityrestaurant.com/',
    'Zip ': '75204',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: '32.8559945, -96.8679547',
    Cuisine: '',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'Mexican Sugar',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': 'Flower Mound',
    'CHEW ': '4',
    City: 'Flower Mound',
    Coordinates: '32.9092692, -96.8683677',
    Cuisine: 'Italian',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'http://www.fioriflowermound.com/menu',
    'Name of Restaurant': 'Fiori',
    Notes: '',
    'Phone #': '14696300096',
    'Referred By': '',
    State: 'TX',
    Street: '1221 Flower Mound Rd Suite 100',
    Website: 'http://www.fioriflowermound.com/',
    'Zip ': '75028',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: '33.0115157, -97.0470608',
    Cuisine: '',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'First Watch',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Argyle',
    Coordinates: '33.1928817, -97.0977116',
    Cuisine: 'Fusion  Pizza Italian BBQ',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': 'http://www.earls377pizza.com/full-menu',
    'Name of Restaurant': "Earl's 377 Pizza",
    Notes: '',
    'Phone #': '19404644444',
    'Referred By': '',
    State: 'TX',
    Street: '427 US-377',
    Website: 'http://www.earls377pizza.com/',
    'Zip ': '76226',
  },
  {
    'Area of Metroplex': 'Irving',
    'CHEW ': '4',
    City: 'Irving',
    Coordinates: '33.0719501, -97.0323923',
    Cuisine: 'Japanese',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'Mr. Max',
    Notes: '',
    'Phone #': '(972) 255 8889',
    'Referred By': '',
    State: 'TX',
    Street: '3028 N Belt Line Road',
    Website: 'https://www.mrmaxtx.com/',
    'Zip ': '75062',
  },
  {
    'Area of Metroplex': 'Farmers Branch Carrollton',
    'CHEW ': '3',
    City: 'Dallas',
    Coordinates: '41.8721463, -87.6335715',
    Cuisine: 'Japanese',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'Fujiyama',
    Notes: '',
    'Phone #': '(972) 662-2885 ',
    'Referred By': '',
    State: 'TX',
    Street: '18217 Midway Rd Suite #108',
    Website: 'www.fujiyamadallas.com',
    'Zip ': '75287',
  },
  {
    'Area of Metroplex': 'Flower Mound',
    'CHEW ': '3.5',
    City: 'Flower Mound',
    Coordinates: '32.9528152, -96.87127269999999',
    Cuisine: 'Chinese',
    'Delivery Services': 'Delivers',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'China Island ',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: 'TX',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3.5',
    City: 'Denton',
    Coordinates: '32.8101097, -96.81047009999999',
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'IG/FB': 'https://www.facebook.com/Taqueria-Guanajuato-379386602183888/',
    'Menu Info':
      'http://places.singleplatform.com/guanajuato-2/menu?ref=google',
    'Name of Restaurant': 'Taqueria Guanajuato',
    Notes: '',
    'Phone #': '19404831598',
    'Referred By': '',
    State: 'TX',
    Street: '1015 E McKinney St',
    Website: '',
    'Zip ': '76209',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '2.5',
    City: 'FTW',
    Coordinates: '33.21464, -97.12966999999999',
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'IG/FB':
      'https://m.facebook.com/Hacienda-Buffet-Forth-Worth-2050912585120773/',
    'Menu Info': '',
    'Name of Restaurant': 'Hacienda Buffet',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: 'TX',
    Street: '1950 Menefee',
    Website: '',
    'Zip ': '76106',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '2.5',
    City: '',
    Coordinates: '47.0110533, 8.3349906',
    Cuisine: 'bakery coffee',
    'Delivery Services': '',
    'IG/FB': '',
    'Menu Info': '',
    'Name of Restaurant': 'Mozart Bakery',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Street: '',
    Website: '',
    'Zip ': '',
  },
];

export default data;
