let data = [
  {
    Address: '3309 Coit Rd #100, Plano, TX 75093, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: 'Plano',
    Coordinates: {latitude: 33.0425716, longitude: -96.7705469},
    Cuisine: 'Taiwanese',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Bull Daddy Bistro',
    Notes: '',
    'Phone #': '19725191088',
    'Referred By': '',
    State: 'TX',
    Website: 'http://www.bulldaddynoodle.com/',
    Zip: '75093',
  },
  {
    Address: '2528 Old Denton Rd Ste.310, Carrollton, TX 75006, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: 'Carrollton',
    Coordinates: {latitude: 32.9798706, longitude: -96.9082913},
    Cuisine: '',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Fat Ni BBQ',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: 'TX',
    Website: 'https://fatni-bbq.com/',
    Zip: '75006',
  },
  {
    Address: '2995 Preston Rd #1590, Frisco, TX 75034, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: 'Frisco',
    Coordinates: {latitude: 33.1038894, longitude: -96.8085861},
    Cuisine: 'Greek',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Platias',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Website: '',
    Zip: '',
  },
  {
    Address: '1000 8th Ave Ste 101, Fort Worth, TX 76104, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: {latitude: 32.7338039, longitude: -97.3439368},
    Cuisine: '',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Boca 31 Fort Worth',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Website: '',
    Zip: '',
  },
  {
    Address: '3039 Old Denton Rd #100, Carrollton, TX 75007, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: 'Carrollton',
    Coordinates: {latitude: 32.9966221, longitude: -96.9104778},
    Cuisine: 'Peruvian',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Munay Rotisserie Chicken',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: 'TX',
    Website: '',
    Zip: '75007',
  },
  {
    Address: '2912 Elm St, Dallas, TX 75226, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: {latitude: 32.7847593, longitude: -96.7819267},
    Cuisine: '',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Buckey Moonshine',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Website: '',
    Zip: '',
  },
  {
    Address: '700 W Dallas Rd, Grapevine, TX 76051, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: 'Grapevine',
    Coordinates: {latitude: 32.9327638, longitude: -97.08272529999999},
    Cuisine: '',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Bread Haus',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: 'TX',
    Website: 'http://www.breadhaus.com/index.html',
    Zip: '76051',
  },
  {
    Address: '2401 W 7th St, Fort Worth, TX 76107, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: 'Fort Worth',
    Coordinates: {latitude: 32.7506901, longitude: -97.3514273},
    Cuisine: 'Vietnamese',
    'IG/FB': '',
    Menu: 'https://www.phodistrictdfw.com/menu',
    'Name of Restaurant': 'Pho District DFW',
    Notes: '',
    'Phone #': '18178629988',
    'Referred By': '',
    State: 'TX',
    Website: 'https://www.phodistrictdfw.com/',
    Zip: '76107',
  },
  {
    Address: '101 S Coit Rd Suite 84, Richardson, TX 75080, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: 'Richardson',
    Coordinates: {latitude: 32.9485869, longitude: -96.76742550000002},
    Cuisine: 'African',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Imperial East African Cuisine',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: 'TX',
    Website: '',
    Zip: '75080',
  },
  {
    Address: '2816 Brown Trail, Bedford, TX 76021, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: 'Bedford',
    Coordinates: {latitude: 32.8517741, longitude: -97.1598348},
    Cuisine: 'Soul Food BBQ Southern',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': "Rosako's Soulfood and BBQ",
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Website: '',
    Zip: '',
  },
  {
    Address: '7110 Main St, Frisco, TX 75033, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: 'Frisco',
    Coordinates: {latitude: 33.1505337, longitude: -96.8225272},
    Cuisine: '',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'The Impractical Sandwich',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: 'TX',
    Website: 'https://theimpracticalsandwich.com/',
    Zip: '75033',
  },
  {
    Address: '6601 Snider Plaza, Dallas, TX 75205, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: 'Dallas',
    Coordinates: {latitude: 32.8468401, longitude: -96.788286},
    Cuisine: 'German',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Kuby’s',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Website: '',
    Zip: '',
  },
  {
    Address: '1901 Abrams Rd, Dallas, TX 75214, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: {latitude: 32.8129772, longitude: -96.75191029999999},
    Cuisine: '',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Petra and The Beast',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Website: '',
    Zip: '',
  },
  {
    Address: '1016 E Hebron Pkwy Ste 140, Carrollton, TX 75010, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: 'Carrollton',
    Coordinates: {latitude: 33.0203359, longitude: -96.9138802},
    Cuisine: 'Chinese',
    'IG/FB': '',
    Menu: 'http://ezordernow.com/mulannoodleandgrill',
    'Name of Restaurant': 'MuLan Noodle and Grill',
    Notes: '',
    'Phone #': '19723957888',
    'Referred By': '',
    State: 'TX',
    Website: 'https://mulannoodlegrill.com/',
    Zip: '75010',
  },
  {
    Address: '9780 Walnut St #340, Dallas, TX 75243, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: {latitude: 32.921727, longitude: -96.71966479999999},
    Cuisine: '',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Bistro B',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Website: '',
    Zip: '',
  },
  {
    Address: '10554 Harry Hines Blvd, Dallas, TX 75220, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: 'Dallas',
    Coordinates: {latitude: 32.8689522, longitude: -96.8819905},
    Cuisine: 'Burger',
    'IG/FB': 'https://www.facebook.com/Kellers-Drive-In-126497860738502/',
    Menu: '',
    'Name of Restaurant': 'Keller’s Drive-In',
    Notes: '',
    'Phone #': '12143573572',
    'Referred By': '',
    State: 'TX',
    Website: '',
    Zip: '75220',
  },
  {
    Address: '1868 Sylvan Ave d100, Dallas, TX 75208, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: {latitude: 32.7689166, longitude: -96.83547229999999},
    Cuisine: 'Italian',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'CiboDivino Marketplace',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Website: '',
    Zip: '',
  },
  {
    Address: '416 N Tyler St, Dallas, TX 75208, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: 'Carrollton',
    Coordinates: {latitude: 32.7487276, longitude: -96.8374127},
    Cuisine: 'Venezuelan Latin',
    'IG/FB': '',
    Menu: 'https://www.orderholacafetexas.com/',
    'Name of Restaurant': 'Hola Cafe',
    Notes: '',
    'Phone #': '19726956363',
    'Referred By': '',
    State: 'TX',
    Website: 'https://www.orderholacafetexas.com/',
    Zip: '75007',
  },
  {
    Address: '2662 N Josey Ln #228, Carrollton, TX 75007, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: 'Carrollton',
    Coordinates: {latitude: 32.9902369, longitude: -96.88864679999999},
    Cuisine: 'Cuban Latin',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Cuban Dulceria International Bakery',
    Notes: '',
    'Phone #': '19722423797',
    'Referred By': '',
    State: 'TX',
    Website: 'http://www.cubanbakerydfw.com/',
    Zip: '75007',
  },
  {
    Address: '701 Commerce St #120, Dallas, TX 75202, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: 'Dallas',
    Coordinates: {latitude: 32.7787323, longitude: -96.805621},
    Cuisine: '',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Chimala Taco Bar',
    Notes: '',
    'Phone #': '972-754-2213',
    'Referred By': '',
    State: 'TX',
    Website: 'https://chimalmatacobar.com/contact-us/',
    Zip: '75202',
  },
  {
    Address: '2001 Bryan St #100, Dallas, TX 75201, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: {latitude: 32.7853501, longitude: -96.79633469999999},
    Cuisine: 'Italian',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'CiboDivino Centro',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Website: '',
    Zip: '',
  },
  {
    Address: '8245 Preston Rd #100, Plano, TX 75024, United States',
    'Area of Metroplex': '121 Preston',
    'CHEW ': '0',
    City: '',
    Coordinates: {latitude: 33.08978889999999, longitude: -96.8065889},
    Cuisine: 'Japanese',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Ikigai Udon',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Website: '',
    Zip: '',
  },
  {
    Address: '119 Ave A, Denton, TX 76201, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: {latitude: 33.2139882, longitude: -97.1459709},
    Cuisine: '',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Poke Loco',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Website: '',
    Zip: '',
  },
  {
    Address: '114 W Oak St, Denton, TX 76201, United States',
    'Area of Metroplex': '',
    'CHEW ': '0',
    City: '',
    Coordinates: {latitude: 33.2156784, longitude: -97.1331998},
    Cuisine: 'Denton',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'West Oak Coffee',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Website: '',
    Zip: '',
  },
  {
    Address: '3802 W Northwest Hwy, Dallas, TX 75220, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: {latitude: 32.8606502, longitude: -96.8530648},
    Cuisine: '',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Bugatti Ristorante',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Website: '',
    Zip: '',
  },
  {
    Address: '603 N Locust St, Denton, TX 76201, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: {latitude: 33.2194599, longitude: -97.1325557},
    Cuisine: '',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Loco Cafe',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Website: '',
    Zip: '',
  },
  {
    Address: '3977 N Belt Line Rd, Irving, TX 75038, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: 'Irving',
    Coordinates: {latitude: 32.8596636, longitude: -96.992682},
    Cuisine: '',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Empa Mundo',
    Notes: '',
    'Phone #': '',
    'Referred By': '',
    State: 'TX',
    Website: 'https://www.empamundo.com/',
    Zip: '75038',
  },
  {
    Address: '2714 Elm St, Dallas, TX 75226, United States',
    'Area of Metroplex': '',
    'CHEW ': '',
    City: '',
    Coordinates: {latitude: 32.7844583, longitude: -96.7841024},
    Cuisine: '',
    'IG/FB': '',
    Menu: '',
    'Name of Restaurant': 'Armoury DE',
    Notes: 'the burger**',
    'Phone #': '',
    'Referred By': '',
    State: '',
    Website: '',
    Zip: '',
  },
];
export default data;
