let data = [
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Lewisville',
    Coordinates: {latitude: 33.0463292, longitude: -96.9941903},
    Cuisine: 'Cajun',
    'Delivery Services': '',
    'Full Address': ', Lewisville,  ',
    'IG/FB': '',
    'Menu Info': '',
    Name: 'Aw Shucks',
    Notes: 'Multiple Locations',
    'Phone #': '',
    State: '',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': 'Lakewood',
    'CHEW ': '3.5',
    City: 'Dallas',
    Coordinates: {latitude: 32.8123251, longitude: -96.76229169999999},
    Cuisine: 'Vietnamese',
    'Delivery Services': '',
    'Full Address': '6047 Lewis St , Dallas, TX 75206',
    'IG/FB': '',
    'Menu Info': 'https://www.mothaibadallas.com/menu',
    Name: 'Mot Hai Ba',
    Notes: '',
    'Phone #': ' (972) 638-7468 ',
    State: 'TX',
    Street: '6047 Lewis St ',
    Website: 'https://www.mothaibadallas.com/',
    'Zip ': '75206',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Flower Mound',
    Coordinates: {latitude: 33.0145673, longitude: -97.0969552},
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'Full Address': ', Flower Mound, TX ',
    'IG/FB': '',
    'Menu Info': '',
    Name: 'Mi Dia',
    Notes: 'Multiple Locations',
    'Phone #': '',
    State: 'TX',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3.5',
    City: 'Dallas',
    Coordinates: {latitude: 32.8973795, longitude: -96.8717779},
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'Full Address': '10909 Webb Chapel Rd #155, Dallas, TX 75229',
    'IG/FB': '',
    'Menu Info': 'https://www.cristinataqueria.com/menu',
    Name: 'Taqueria Cristina',
    Notes: '',
    'Phone #': '12143580015',
    State: 'TX',
    Street: '10909 Webb Chapel Rd #155',
    Website: 'https://www.cristinataqueria.com/',
    'Zip ': '75229',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '2.5',
    City: 'Carrollton',
    Coordinates: {latitude: 32.951582, longitude: -96.90839899999999},
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'Full Address': '1114 Elm St #100, Carrollton, TX 75006',
    'IG/FB': '',
    'Menu Info':
      'https://www.elrincontx.com/carrollton/?utm_source=google&utm_medium=gmbmenu&utm_campaign=Carrollton&utm_term=mexicanrestaurant&utm_content=idgmb',
    Name: 'EL Rincon Mexican Kitchen & Tequila Bar - Carrollton Location',
    Notes: '',
    'Phone #': '14698926429',
    State: 'TX',
    Street: '1114 Elm St #100',
    Website:
      'https://www.elrincontx.com/carrollton/?utm_source=google&utm_medium=gmbhome&utm_campaign=Carrollton&utm_term=mexicanrestaurant&utm_content=idgmb',
    'Zip ': '75006',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Irving',
    Coordinates: {latitude: 32.8877661, longitude: -96.9636531},
    Cuisine: 'Japanese',
    'Delivery Services': '',
    'Full Address': '1030 W John Carpenter Fwy #100, Irving, TX 75039',
    'IG/FB': '',
    'Menu Info': 'https://edokolascolinas.com/food-menu',
    Name: 'Edoko Omakase',
    Notes: '',
    'Phone #': '19726008626',
    State: 'TX',
    Street: '1030 W John Carpenter Fwy #100',
    Website: 'https://edokolascolinas.com/',
    'Zip ': '75039',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '2.5',
    City: 'FTW',
    Coordinates: {latitude: 32.7885964, longitude: -97.38365069999999},
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'Full Address': '1950 Menefee, FTW, TX 76106',
    'IG/FB':
      'https://m.facebook.com/Hacienda-Buffet-Forth-Worth-2050912585120773/',
    'Menu Info': '',
    Name: 'Hacienda Buffet',
    Notes: '',
    'Phone #': '',
    State: 'TX',
    Street: '1950 Menefee',
    Website: '',
    'Zip ': '76106',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Dallas',
    Coordinates: {latitude: 32.8215641, longitude: -96.7869963},
    Cuisine: 'Mediterranean',
    'Delivery Services': '',
    'Full Address': '3001 Knox St #110, Dallas, TX 75205',
    'IG/FB': '',
    'Menu Info':
      'http://places.singleplatform.com/fadis-mediterranean-grill/menu?ref=google',
    Name: "Fadi's Mediterranean Grill",
    Notes: 'Multiple Locations',
    'Phone #': '12145281800',
    State: 'TX',
    Street: '3001 Knox St #110',
    Website: 'http://www.fadiscuisine.com/',
    'Zip ': '75205',
  },
  {
    'Area of Metroplex': 'North Dallas/Richardson',
    'CHEW ': '4',
    City: 'Richardson',
    Coordinates: {latitude: 32.9483335, longitude: -96.7298519},
    Cuisine: 'Chinese',
    'Delivery Services': '',
    'Full Address': ', Richardson, TX ',
    'IG/FB': '',
    'Menu Info': '',
    Name: 'Jeng Chi',
    Notes: 'Dumplings, Juices, ',
    'Phone #': '',
    State: 'TX',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '4',
    City: 'Plano',
    Coordinates: {latitude: 33.0455465, longitude: -96.7025482},
    Cuisine: 'German',
    'Delivery Services': '',
    'Full Address': '3425 Premier Dr, Plano TX, Plano, TX 75023',
    'IG/FB': '',
    'Menu Info': 'https://bavariangrill.com/core-menu/',
    Name: 'Bavarian Grill',
    Notes: '',
    'Phone #': '19728810705',
    State: 'TX',
    Street: '3425 Premier Dr, Plano TX',
    Website: 'http://www.bavariangrill.com/',
    'Zip ': '75023',
  },
  {
    'Area of Metroplex': 'Irving',
    'CHEW ': '4',
    City: 'Irving',
    Coordinates: {latitude: 32.8483026, longitude: -96.991508},
    Cuisine: 'Japanese',
    'Delivery Services': '',
    'Full Address': '3028 N Belt Line Road, Irving, TX 75062',
    'IG/FB': '',
    'Menu Info': '',
    Name: 'Mr. Max',
    Notes: '',
    'Phone #': '(972) 255 8889',
    State: 'TX',
    Street: '3028 N Belt Line Road',
    Website: 'https://www.mrmaxtx.com/',
    'Zip ': '75062',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '4',
    City: 'Richardson',
    Coordinates: {latitude: 32.9495286, longitude: -96.73392679999999},
    Cuisine: 'Chinese',
    'Delivery Services': '',
    'Full Address': '200 W Polk St A, Richardson, TX 75081',
    'IG/FB': '',
    'Menu Info':
      'http://places.singleplatform.com/first-emperor-barbecue-chinese-restaurant/menu?ref=google',
    Name: 'First Emperor Chinese Restaurant',
    Notes: '',
    'Phone #': '19726809077',
    State: 'TX',
    Street: '200 W Polk St A',
    Website: 'http://www.firstemperorchinese.com/',
    'Zip ': '75081',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3.5',
    City: 'Dallas',
    Coordinates: {latitude: 32.8319881, longitude: -96.77051999999999},
    Cuisine: 'Mediterranean',
    'Delivery Services': '',
    'Full Address': '3711 Greenville Ave., Dallas, TX 75206',
    'IG/FB': '',
    'Menu Info': 'https://cafeizmir.com/menu',
    Name: 'Cafe Izmir Mediterranean Tapas',
    Notes: '',
    'Phone #': '12148267788',
    State: 'TX',
    Street: '3711 Greenville Ave.',
    Website: 'http://www.cafeizmir.com/',
    'Zip ': '75206',
  },
  {
    'Area of Metroplex': 'Forth Worth 7th Street',
    'CHEW ': '4',
    City: 'Fort Worth',
    Coordinates: {latitude: 32.7496784, longitude: -97.3560994},
    Cuisine: 'Japanese Sushi',
    'Delivery Services': '',
    'Full Address': '907 Foch St, Fort Worth, TX 76107',
    'IG/FB': 'http://instagram.com/HatsuyukiFW',
    'Menu Info': '',
    Name: 'Hatsuyuki Handroll Bar',
    Notes: '',
    'Phone #': '18177205330',
    State: 'TX',
    Street: '907 Foch St',
    Website: '',
    'Zip ': '76107',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '4',
    City: 'Argyle',
    Coordinates: {latitude: 33.1002911, longitude: -97.21353970000001},
    Cuisine: 'American BBQ Texas BBQ',
    'Delivery Services': '',
    'Full Address': '831 FM 407 W., Argyle, TX 76226',
    'IG/FB': 'https://www.instagram.com/407bbq/',
    'Menu Info': 'http://407bbq.com/',
    Name: '407 BBQ',
    Notes: '',
    'Phone #': '(682) 224-9225 ',
    State: 'TX',
    Street: '831 FM 407 W.',
    Website: 'http://407bbq.com/',
    'Zip ': '76226',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '2.5',
    City: 'Highland Village',
    Coordinates: {latitude: 33.073911, longitude: -97.07942249999999},
    Cuisine: 'Seafood Asian Poke',
    'Delivery Services': '',
    'Full Address': '3090 Justin Rd #305, Highland Village, TX 75077',
    'IG/FB': '',
    'Menu Info':
      'https://order.snackpass.co/Pokemoto-(Highland-Village-3090-Justin-Road)-63913dc77e78ab00a8861e22',
    Name: 'Pokemoto',
    Notes: '',
    'Phone #': '14696300030',
    State: 'TX',
    Street: '3090 Justin Rd #305',
    Website: 'http://www.pokemoto.com/',
    'Zip ': '75077',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3.5',
    City: 'Lewisville',
    Coordinates: {latitude: 33.0355884, longitude: -97.01099579999999},
    Cuisine: 'Latin Salvadorian',
    'Delivery Services': '',
    'Full Address': '1003 Fox Ave suite 140, Lewisville, TX 75067',
    'IG/FB': '',
    'Menu Info': 'https://www.pupuseriayantojitosonfox.com/menu',
    Name: 'Pupuseria Y Antojitos',
    Notes: '',
    'Phone #': '12142224040',
    State: 'TX',
    Street: '1003 Fox Ave suite 140',
    Website: '',
    'Zip ': '75067',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Argyle',
    Coordinates: {latitude: 33.1025656, longitude: -97.1892762},
    Cuisine: 'Coffee Sandwiches',
    'Delivery Services': '',
    'Full Address': '429 US-377, Argyle, TX 76226',
    'IG/FB': '',
    'Menu Info':
      'http://places.singleplatform.com/kimzeys-coffee-shop/menu?ref=google',
    Name: "Kimzey's Coffee",
    Notes: '',
    'Phone #': '19402401001',
    State: 'TX',
    Street: '429 US-377',
    Website: 'http://www.kimzeys.com/',
    'Zip ': '76226',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3.5',
    City: 'Denton',
    Coordinates: {latitude: 33.1928817, longitude: -97.0977116},
    Cuisine: 'Seafood  ',
    'Delivery Services': '',
    'Full Address': '1716 S Loop 288 Suite 110, Denton, TX 76208',
    'IG/FB': '',
    'Menu Info': 'https://www.cocoshrimp.com/menu',
    Name: 'Coco Shrimp ',
    Notes: '',
    'Phone #': '',
    State: 'TX',
    Street: '1716 S Loop 288 Suite 110',
    Website: 'https://www.cocoshrimp.com/',
    'Zip ': '76208',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Denton',
    Coordinates: {latitude: 33.2142448, longitude: -97.1331589},
    Cuisine: 'Burger ',
    'Delivery Services': '',
    'Full Address': '113 W Hickory St, Denton, TX 76201',
    'IG/FB': '',
    'Menu Info': 'https://www.lsaburger.com/good-eats',
    Name: 'LSA Burger Co.',
    Notes: '',
    'Phone #': '19403831022',
    State: 'TX',
    Street: '113 W Hickory St',
    Website: 'http://www.lsaburger.com/',
    'Zip ': '76201',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '4',
    City: 'Flower Mound',
    Coordinates: {latitude: 33.0346696, longitude: -97.0712626},
    Cuisine: 'Pizza',
    'Delivery Services': 'yes',
    'Full Address': '2704 Cross Timbers Rd Suite 112, Flower Mound, TX 75028',
    'IG/FB': '',
    'Menu Info': 'https://www.rosatispizza.com/location/flower-mound-tx/',
    Name: 'Rosati’s',
    Notes: 'Multiple Locations',
    'Phone #': '19729069696',
    State: 'TX',
    Street: '2704 Cross Timbers Rd Suite 112',
    Website: 'https://www.rosatispizza.com/location/flower-mound-tx/',
    'Zip ': '75028',
  },
  {
    'Area of Metroplex': 'Loop12/35E',
    'CHEW ': '3',
    City: 'Dallas',
    Coordinates: {latitude: 32.7766642, longitude: -96.79698789999999},
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'Full Address': ', Dallas, TX ',
    'IG/FB': '',
    'Menu Info': '',
    Name: 'Cabrisitos',
    Notes: '',
    'Phone #': '',
    State: 'TX',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Denton',
    Coordinates: {latitude: 33.2150186, longitude: -97.13410789999999},
    Cuisine: 'Southern',
    'Delivery Services': '',
    'Full Address': '111 N Elm St, Denton, TX 76201',
    'IG/FB': '',
    'Menu Info': 'https://cartwrightsranchhouse.takeout7.com/',
    Name: "Cartwright's Ranch House",
    Notes: '',
    'Phone #': '19403877706',
    State: 'TX',
    Street: '111 N Elm St',
    Website: 'http://www.cartwrightstexas.com/',
    'Zip ': '76201',
  },
  {
    'Area of Metroplex': 'Lewisville',
    'CHEW ': '3.5',
    City: 'Lewisville',
    Coordinates: {latitude: 33.0474684, longitude: -96.99780020000001},
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'Full Address': '253 W Church St , Lewisville, TX 75057',
    'IG/FB': '',
    'Menu Info': 'https://palapasseafoodbar.us//menu.php',
    Name: 'Palapas Seafood Bar',
    Notes: '',
    'Phone #': '945-228-0441 ',
    State: 'TX',
    Street: '253 W Church St ',
    Website: 'https://palapasseafoodbar.us/',
    'Zip ': '75057',
  },
  {
    'Area of Metroplex': 'Uptown?',
    'CHEW ': '3.5',
    City: 'Dallas',
    Coordinates: {latitude: 32.7766642, longitude: -96.79698789999999},
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'Full Address': ', Dallas, TX ',
    'IG/FB': '',
    'Menu Info': '',
    Name: 'Javiers',
    Notes: '',
    'Phone #': '',
    State: 'TX',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Irving',
    Coordinates: {latitude: 32.9409147, longitude: -96.9516392},
    Cuisine: 'Mexican Taqueria',
    'Delivery Services': '',
    'Full Address': '10000 N MacArthur Blvd,, Irving, TX 75063',
    'IG/FB': 'https://m.facebook.com/SanDiegoTacos/',
    'Menu Info':
      'http://places.singleplatform.com/san-diego-taco-shop-0/menu?ref=google',
    Name: 'San Diego Tacos',
    Notes: 'Multiple Locations',
    'Phone #': '19725067064',
    State: 'TX',
    Street: '10000 N MacArthur Blvd,',
    Website: '',
    'Zip ': '75063',
  },
  {
    'Area of Metroplex': 'Downtown Dallas',
    'CHEW ': '4',
    City: 'Dallas',
    Coordinates: {latitude: 32.7991667, longitude: -96.7794444},
    Cuisine: 'Thai',
    'Delivery Services': '',
    'Full Address': '4301 Bryan St #101, Dallas, TX 75204',
    'IG/FB': '',
    'Menu Info': 'http://www.bangkokcityrestaurant.com/',
    Name: 'Bangkok City Restaurant',
    Notes: '',
    'Phone #': '12148246200',
    State: 'TX',
    Street: '4301 Bryan St #101',
    Website: 'https://www.bangkokcityrestaurant.com/',
    'Zip ': '75204',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Lewisville',
    Coordinates: {latitude: 33.0719501, longitude: -97.0323923},
    Cuisine: 'Pizza',
    'Delivery Services': '',
    'Full Address': '1425 FM 407 Suite 600, Lewisville, TX 75077',
    'IG/FB': '',
    'Menu Info': '',
    Name: 'Motor City Pizza',
    Notes: '',
    'Phone #': '19726546276',
    State: 'TX',
    Street: '1425 FM 407 Suite 600',
    Website: 'https://www.motorcitypizzatx.com/',
    'Zip ': '75077',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Argyle',
    Coordinates: {latitude: 33.1028218, longitude: -97.1897604},
    Cuisine: 'Fusion  Pizza Italian BBQ',
    'Delivery Services': '',
    'Full Address': '427 US-377, Argyle, TX 76226',
    'IG/FB': '',
    'Menu Info': 'http://www.earls377pizza.com/full-menu',
    Name: "Earl's 377 Pizza",
    Notes: '',
    'Phone #': '19404644444',
    State: 'TX',
    Street: '427 US-377',
    Website: 'http://www.earls377pizza.com/',
    'Zip ': '76226',
  },
  {
    'Area of Metroplex': 'Addison Farmers Branch',
    'CHEW ': '3.5',
    City: 'Carrollton',
    Coordinates: {latitude: 32.9528152, longitude: -96.87127269999999},
    Cuisine: 'Latin Cuban',
    'Delivery Services': '',
    'Full Address': '1000 Webb Chapel Rd, Carrollton, TX 75006',
    'IG/FB': '@caribbean_cuba',
    'Menu Info': '',
    Name: 'Caribbean Cuba Cafe',
    Notes: '',
    'Phone #': '(469) 758-6047 ',
    State: 'TX',
    Street: '1000 Webb Chapel Rd',
    Website: 'http://mycaribbeancuba.com/',
    'Zip ': '75006',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Carrollton',
    Coordinates: {latitude: 32.9892425, longitude: -96.86684419999999},
    Cuisine: 'Central American Salvadorian',
    'Delivery Services': '',
    'Full Address': '2660 Kelly Blvd, Carrollton, TX 75007',
    'IG/FB': '',
    'Menu Info': 'http://orderrestaurantlatinotx.com/',
    Name: 'Restaurant Latino',
    Notes: 'Papusas',
    'Phone #': '19724167195',
    State: 'TX',
    Street: '2660 Kelly Blvd',
    Website: '',
    'Zip ': '75007',
  },
  {
    'Area of Metroplex': 'Northwest Dallas',
    'CHEW ': '3.5',
    City: 'Dallas',
    Coordinates: {latitude: 32.8805181, longitude: -96.88088359999999},
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'Full Address': '2900 Wallnut Hill Ln, Ste 202 , Dallas, TX 75229',
    'IG/FB': '',
    'Menu Info': 'https://elrincondeldf.com/menu/',
    Name: 'El Rincon del D.F. (LaCapital de la Torta)',
    Notes: '',
    'Phone #': '214-350-0381 ',
    State: 'TX',
    Street: '2900 Wallnut Hill Ln, Ste 202 ',
    Website: 'https://elrincondeldf.com/',
    'Zip ': '75229',
  },
  {
    'Area of Metroplex': 'Flower Mound',
    'CHEW ': '4',
    City: 'Flower Mound',
    Coordinates: {latitude: 33.0115157, longitude: -97.0470608},
    Cuisine: 'Italian',
    'Delivery Services': '',
    'Full Address': '1221 Flower Mound Rd Suite 100, Flower Mound, TX 75028',
    'IG/FB': '',
    'Menu Info': 'http://www.fioriflowermound.com/menu',
    Name: 'Fiori',
    Notes: '',
    'Phone #': '14696300096',
    State: 'TX',
    Street: '1221 Flower Mound Rd Suite 100',
    Website: 'http://www.fioriflowermound.com/',
    'Zip ': '75028',
  },
  {
    'Area of Metroplex': 'Dallas Deep Ellum',
    'CHEW ': '4',
    City: 'Dallas',
    Coordinates: {latitude: 32.7845293, longitude: -96.7829254},
    Cuisine: 'Japanese',
    'Delivery Services': '',
    'Full Address': '2814 Elm St, Dallas, TX 75226',
    'IG/FB': '',
    'Menu Info': 'http://www.norihandrollbar.com/menu',
    Name: 'Nori Handroll Bar',
    Notes: '',
    'Phone #': '14694366674',
    State: 'TX',
    Street: '2814 Elm St',
    Website: 'http://www.norihandrollbar.com/',
    'Zip ': '75226',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3.5',
    City: 'Flower Mound',
    Coordinates: {latitude: 33.0363765, longitude: -97.0745118},
    Cuisine: 'Mediterranean',
    'Delivery Services': '',
    'Full Address': '2911 Cross Timbers Rd #103, Flower Mound, TX 75028',
    'IG/FB': '',
    'Menu Info': 'http://istanbulflowermound.com/',
    Name: 'Istanbul Cuisine Flower Mound',
    Notes: '',
    'Phone #': '12145131333',
    State: 'TX',
    Street: '2911 Cross Timbers Rd #103',
    Website: 'https://www.istanbulflowermound.com/',
    'Zip ': '75028',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '4',
    City: 'South Lake',
    Coordinates: {latitude: 32.9399092, longitude: -97.1113342},
    Cuisine: 'Chinese',
    'Delivery Services': '',
    'Full Address': '2640 E Southlake Blvd, South Lake, TX 76092',
    'IG/FB': '',
    'Menu Info':
      'https://www.foodbooking.com/ordering/restaurant/menu?restaurant_uid=75a1737d-b777-48cf-80c0-60a2b261d25b',
    Name: 'Dragon House',
    Notes: '',
    'Phone #': '18179121788',
    State: 'TX',
    Street: '2640 E Southlake Blvd',
    Website: 'http://www.dragonhousesouthlake.com/',
    'Zip ': '76092',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Denton',
    Coordinates: {latitude: 33.2314399, longitude: -97.1340658},
    Cuisine: 'Greek Mediterranean',
    'Delivery Services': '',
    'Full Address': '210 W University Dr ive, Denton, TX 76201',
    'IG/FB': '',
    'Menu Info': '',
    Name: "Yummy's Greek ",
    Notes: '',
    'Phone #': '(940) 383-2441 ',
    State: 'TX',
    Street: '210 W University Dr ive',
    Website: 'https://www.yummysgreekfood.com/',
    'Zip ': '76201',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3.5',
    City: 'Bedford',
    Coordinates: {latitude: 32.844017, longitude: -97.1430671},
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'Full Address': ', Bedford, TX ',
    'IG/FB': '',
    'Menu Info': '',
    Name: 'Il Paesa',
    Notes: 'Multiple Locations',
    'Phone #': '',
    State: 'TX',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '4',
    City: 'Denton',
    Coordinates: {latitude: 33.1841222, longitude: -97.1075178},
    Cuisine: 'Hamburger',
    'Delivery Services': '',
    'Full Address': '2430 S Interstate 35 Ste 172, Denton, TX 76205',
    'IG/FB': '',
    'Menu Info':
      'http://places.singleplatform.com/rg-burgers--grill/menu?ref=google',
    Name: 'RG Burgers and Grill',
    Notes: '',
    'Phone #': '19403832431',
    State: 'TX',
    Street: '2430 S Interstate 35 Ste 172',
    Website: 'https://www.rgtexas.com/',
    'Zip ': '76205',
  },
  {
    'Area of Metroplex': 'Farmers Branch Carrollton',
    'CHEW ': '3',
    City: 'Dallas',
    Coordinates: {latitude: 32.9986014, longitude: -96.84512509999999},
    Cuisine: 'Japanese',
    'Delivery Services': '',
    'Full Address': '18217 Midway Rd Suite #108, Dallas, TX 75287',
    'IG/FB': '',
    'Menu Info': '',
    Name: 'Fujiyama',
    Notes: '',
    'Phone #': '(972) 662-2885 ',
    State: 'TX',
    Street: '18217 Midway Rd Suite #108',
    Website: 'www.fujiyamadallas.com',
    'Zip ': '75287',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '2.5',
    City: 'Dallas',
    Coordinates: {latitude: 32.8559945, longitude: -96.8679547},
    Cuisine: 'Mexican Seafood',
    'Delivery Services': '',
    'Full Address': '9404 Ovella Ave, Dallas, TX 75220',
    'IG/FB': '',
    'Menu Info': 'http://www.mariscoslamarea.com/menu',
    Name: 'Mariscos La Marina',
    Notes: '',
    'Phone #': '12143660703',
    State: 'TX',
    Street: '9404 Ovella Ave',
    Website: 'http://mariscoslamarina.com/',
    'Zip ': '75220',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3.5',
    City: 'Denton',
    Coordinates: {latitude: 33.2163211, longitude: -97.1205226},
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'Full Address': '1015 E McKinney St, Denton, TX 76209',
    'IG/FB': 'https://www.facebook.com/Taqueria-Guanajuato-379386602183888/',
    'Menu Info':
      'http://places.singleplatform.com/guanajuato-2/menu?ref=google',
    Name: 'Taqueria Guanajuato',
    Notes: '',
    'Phone #': '19404831598',
    State: 'TX',
    Street: '1015 E McKinney St',
    Website: '',
    'Zip ': '76209',
  },
  {
    'Area of Metroplex': 'Addison',
    'CHEW ': '4',
    City: 'Addison',
    Coordinates: {latitude: 32.9547314, longitude: -96.8442185},
    Cuisine: 'Seafood General Cuisine',
    'Delivery Services': '',
    'Full Address': '4021 Belt Line Rd, Addison, TX 75001',
    'IG/FB': '@leftyslobster',
    'Menu Info': '',
    Name: 'Lefty’s ',
    Notes: '',
    'Phone #': '(972) 774-9518',
    State: 'TX',
    Street: '4021 Belt Line Rd',
    Website: 'http://www.leftyslobster.com/',
    'Zip ': '75001',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Dallas',
    Coordinates: {latitude: 32.81521060000001, longitude: -96.8270816},
    Cuisine: 'Burger Sandwiches',
    'Delivery Services': '',
    'Full Address': '4810 Maple Ave, Dallas, TX 75219',
    'IG/FB': '',
    'Menu Info':
      'http://places.singleplatform.com/maple-and-motor/menu?ref=google',
    Name: 'Maple & Motor',
    Notes: '',
    'Phone #': '12145224400',
    State: 'TX',
    Street: '4810 Maple Ave',
    Website: 'http://mapleandmotor.com/',
    'Zip ': '75219',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Dallas',
    Coordinates: {latitude: 32.7971593, longitude: -96.77371},
    Cuisine: 'Southern',
    'Delivery Services': '',
    'Full Address': '4505 Gaston Ave, Dallas, TX 75246',
    'IG/FB': '',
    'Menu Info': 'https://www.luckyshotchicken.com/menu/',
    Name: 'Lucky’s Hot Chicken',
    Notes: '',
    'Phone #': '12144437927',
    State: 'TX',
    Street: '4505 Gaston Ave',
    Website: 'https://www.luckyshotchicken.com/',
    'Zip ': '75246',
  },
  {
    'Area of Metroplex': 'Downtown Denton',
    'CHEW ': '3.5',
    City: 'Denton',
    Coordinates: {latitude: 33.21464, longitude: -97.12966999999999},
    Cuisine: 'Greek Mediterranean',
    'Delivery Services': '',
    'Full Address': '311 E Hickory St #110 , Denton, TX 76201',
    'IG/FB': '@gyrothreesixty ',
    'Menu Info': '',
    Name: 'Gyro 360',
    Notes: '',
    'Phone #': '(940) 323-0003 ',
    State: 'TX',
    Street: '311 E Hickory St #110 ',
    Website: 'https://www.gyro360tx.com/ ',
    'Zip ': '76201',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '4',
    City: 'Highland Village',
    Coordinates: {latitude: 33.0732863, longitude: -97.08089729999999},
    Cuisine: 'General Fine Dining',
    'Delivery Services': '',
    'Full Address': '3140 FM 407, Highland Village, TX 75077',
    'IG/FB': '',
    'Menu Info': 'https://www.hillsidegrillhighlandvillage.com/menu/',
    Name: 'Hillside Fine Grill',
    Notes: 'Multiple Locations',
    'Phone #': '19723179711',
    State: 'TX',
    Street: '3140 FM 407',
    Website: 'https://www.hillsidegrillhighlandvillage.com/',
    'Zip ': '75077',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3.5',
    City: 'Dallas',
    Coordinates: {latitude: 32.822341, longitude: -96.83589119999999},
    Cuisine: 'Japanese',
    'Delivery Services': '',
    'Full Address': '2555 Inwood Rd #139, Dallas, TX 75235',
    'IG/FB': '',
    'Menu Info':
      'https://www.ubereats.com/store/ichiro-sapporo-ramen/HnC85Be0W2ePqBIqFJBhTw?diningMode=DELIVERY&sc=SEARCH_SUGGESTION',
    Name: 'Ichiro Sapporo Ramen',
    Notes: '',
    'Phone #': '14693726424',
    State: 'TX',
    Street: '2555 Inwood Rd #139',
    Website: '',
    'Zip ': '75235',
  },
  {
    'Area of Metroplex': 'Denton',
    'CHEW ': '3.5',
    City: 'Denton',
    Coordinates: {latitude: 33.1896897, longitude: -97.1253241},
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'Full Address': '630 Londonderry Lane, Denton, TX 76205',
    'IG/FB': '',
    'Menu Info': '',
    Name: 'La Laguna Meat Market & Kitchen',
    Notes: '',
    'Phone #': '',
    State: 'TX',
    Street: '630 Londonderry Lane',
    Website: '',
    'Zip ': '76205',
  },
  {
    'Area of Metroplex': 'Multiple Locations',
    'CHEW ': '2.5',
    City: 'Lewisville',
    Coordinates: {latitude: 33.0463292, longitude: -96.9941903},
    Cuisine: 'Japanese Ramen',
    'Delivery Services': '',
    'Full Address': ', Lewisville, TX ',
    'IG/FB': '',
    'Menu Info': '',
    Name: 'Hakata Ramen',
    Notes: 'Multiple Locations',
    'Phone #': '',
    State: 'TX',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': 'Stockyards',
    'CHEW ': '3.5',
    City: 'Fort Worth',
    Coordinates: {latitude: 32.7845813, longitude: -97.34832209999999},
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'Full Address': '2201 N Commerce St, Fort Worth, TX 76164',
    'IG/FB': '',
    'Menu Info': 'https://mailchi.mp/52e830c3ab45/joetmenu',
    Name: "Joe T. Garcia's",
    Notes: '',
    'Phone #': '18176264356',
    State: 'TX',
    Street: '2201 N Commerce St',
    Website: 'http://joetgarcias.com/',
    'Zip ': '76164',
  },
  {
    'Area of Metroplex': 'Flower Mound',
    'CHEW ': '3.5',
    City: 'Flower Mound',
    Coordinates: {latitude: 33.0145673, longitude: -97.0969552},
    Cuisine: 'Chinese',
    'Delivery Services': 'Delivers',
    'Full Address': ', Flower Mound, TX ',
    'IG/FB': '',
    'Menu Info': '',
    Name: 'China Island ',
    Notes: '',
    'Phone #': '',
    State: 'TX',
    Street: '',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': 'Denton',
    'CHEW ': '3',
    City: 'Denton',
    Coordinates: {latitude: 33.1588514, longitude: -97.10469529999999},
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'Full Address': '3969 Teasley Lane Suite 1300, Denton, TX 76210',
    'IG/FB': '',
    'Menu Info': '',
    Name: 'La Fondita',
    Notes: '',
    'Phone #': '',
    State: 'TX',
    Street: '3969 Teasley Lane Suite 1300',
    Website: '',
    'Zip ': '76210',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3.5',
    City: 'Flower Mound',
    Coordinates: {latitude: 32.9942772, longitude: -97.06522439999999},
    Cuisine: 'Italian',
    'Delivery Services': '',
    'Full Address': '2450 Lakeside Pkwy #100, Flower Mound, TX 75022',
    'IG/FB': '',
    'Menu Info': '',
    Name: 'Mio Nonno Trattoria',
    Notes: '',
    'Phone #': '14698047472',
    State: 'TX',
    Street: '2450 Lakeside Pkwy #100',
    Website: 'http://miononno.com/',
    'Zip ': '75022',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3.5',
    City: 'Argyle',
    Coordinates: {latitude: 33.1030447, longitude: -97.1891184},
    Cuisine: 'American BBQ Texas BBQ',
    'Delivery Services': '',
    'Full Address': '425 US-377 SOUTH, Argyle, TX 76226',
    'IG/FB': '',
    'Menu Info': 'https://www.bumbershootbbq.com/menu-1',
    Name: 'Bumbershoot Barbecue',
    Notes: '',
    'Phone #': '',
    State: 'TX',
    Street: '425 US-377 SOUTH',
    Website: 'https://www.bumbershootbbq.com/',
    'Zip ': '76226',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '3',
    City: 'Denton',
    Coordinates: {latitude: 33.2216583, longitude: -97.13255149999999},
    Cuisine: 'Italian',
    'Delivery Services': '',
    'Full Address': '821 N Locust St #6921, Denton, TX 76201',
    'IG/FB': '',
    'Menu Info': 'https://www.giuseppesitaliana.com/Dinner_Menu.html',
    Name: 'Giuseppe’s',
    Notes: '',
    'Phone #': '19403812712',
    State: 'TX',
    Street: '821 N Locust St #6921',
    Website: 'http://www.giuseppesitaliana.com/',
    'Zip ': '76201',
  },
  {
    'Area of Metroplex': '',
    'CHEW ': '4',
    City: 'Dallas',
    Coordinates: {latitude: 32.9092692, longitude: -96.8683677},
    Cuisine: 'Mexican',
    'Delivery Services': '',
    'Full Address': '3318 Forest Ln #100, Dallas, TX 75234',
    'IG/FB': '',
    'Menu Info': '',
    Name: 'El Tiz Tizoncito Forest',
    Notes: 'Multiple Locations',
    'Phone #': '19722478797',
    State: 'TX',
    Street: '3318 Forest Ln #100',
    Website: 'http://www.tiztaco.com/',
    'Zip ': '75234',
  },
  {
    'Area of Metroplex': 'Little Korea Carrollton',
    'CHEW ': '3',
    City: 'Carrollton',
    Coordinates: {latitude: 32.9862133, longitude: -96.9126974},
    Cuisine: 'Korean',
    'Delivery Services': '',
    'Full Address': '2625 Old Denton Rd #322 , Carrollton, TX 75056',
    'IG/FB': '',
    'Menu Info': 'https://www.ddongggotx.com/menu',
    Name: 'Butt Hole Chicken (DDONG GGO TX)',
    Notes: '',
    'Phone #': '',
    State: 'TX',
    Street: '2625 Old Denton Rd #322 ',
    Website: 'https://www.ddongggotx.com/',
    'Zip ': '75056',
  },
  {
    'Area of Metroplex': 'Athens/East TX',
    'CHEW ': '3.5',
    City: 'Athens',
    Coordinates: {latitude: 32.1949801, longitude: -95.85479819999999},
    Cuisine: 'Coffee Sandwiches',
    'Delivery Services': '',
    'Full Address': '613 S. Prairieville, Athens, TX ',
    'IG/FB': '',
    'Menu Info': '',
    Name: 'Callaway Coffee Bistro',
    Notes: '',
    'Phone #': '',
    State: 'TX',
    Street: '613 S. Prairieville',
    Website: '',
    'Zip ': '',
  },
  {
    'Area of Metroplex': 'Downtown Denton',
    'CHEW ': '3.5',
    City: 'Denton',
    Coordinates: {latitude: 33.214774, longitude: -97.13473049999999},
    Cuisine: 'Middle Eastern/Jordanian',
    'Delivery Services': '',
    'Full Address': '222 W Hickory St #104, Denton, TX 76201',
    'IG/FB': 'https://www.facebook.com/1503921746492828',
    'Menu Info': 'https://www.layalinamediterraneanrestaurant.com/menu/',
    Name: 'Layalina Mediterranean Restaurant and Lounge',
    Notes: '',
    'Phone #': '19403823663',
    State: 'TX',
    Street: '222 W Hickory St #104',
    Website: '',
    'Zip ': '76201',
  },
  {
    'Area of Metroplex': 'Dallas  ',
    'CHEW ': '4',
    City: 'Dallas',
    Coordinates: {latitude: 32.8101097, longitude: -96.81047009999999},
    Cuisine: 'Southern',
    'Delivery Services': '',
    'Full Address': '3857 Cedar Springs Rd, Dallas, TX 75219',
    'IG/FB': '',
    'Menu Info': 'https://www.streetsfinechicken.com/menu-cedar-springs',
    Name: 'Streets Fine Chicken',
    Notes: 'Multiple Locations/Amazing Fried Chicken',
    'Phone #': '',
    State: 'TX',
    Street: '3857 Cedar Springs Rd',
    Website: 'https://www.streetsfinechicken.com/',
    'Zip ': '75219',
  },
];

export default data;
